version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew

      # Pull down the project’s dependencies.
      # Normally you never call this task directly since it’s done automatically when it’s needed,
      # but calling it directly allows us to insert a save_cache step that will store the dependencies
      # in order to speed things up for next time
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Unit tests
          command: ./gradlew testRelease
      - run:
          name: Test coverage report
          command: ./gradlew testCoverageReport
      - store_artifacts:
          path: app/build/reports/jacoco/testCoverageReport/html/
          destination: jacoco
      - run:
          name: Check Android home
          command: echo $ANDROID_HOME
